#  sql :engine mysql  :dbuser org-mode :dbpassword org-mode :database testdb :exports both

​1. Выполнить экспорт данных в формате csv, json и xml из трех таблиц (выбрать любые 3 таблицы из индивидуального задания). В отчете представить скриншоты с содержимым экспортированных файлов.


#+begin_src sql :engine mysql  :dbuser org-mode :dbpassword org-mode :database computerserviceooo :exports results :eval no-export :colnames no
  SELECT id, last_name as 'Фамилия', first_name as 'Имя', second_name as 'Отчество', date_of_birth as 'Дата рождения', sex as 'Пол', address as 'Адрес', phone_number as 'Телефон', passport_details as 'Паспорт', position_id as "Должность" FROM employee;
#+end_src

#+begin_export latex
\begin{footnotesize}
#+end_export
#+CAPTION: Таблица сотрудников
#+ATTR_LATEX: :environment longtable :align |p{0.3cm}|p{1.5cm}|p{1.5cm}|p{2cm}|p{2cm}|p{0.3cm}|p{1.8cm}|p{2.2cm}|p{1cm}|p{0.3cm}|
#+RESULTS:
|  1 | Панков    | Василий | Дмитриевич | 2003-12-15 12:10:59 | 1 | Суховский переулок 23      | +79627011087 | 1111 111111 | 1 |
|  2 | Гайкин    | Кирилл  | Денисович  | 1999-07-17 12:11:08 | 1 | Кобринская улица 5         | +79118445162 | 2222 222222 | 2 |
|  3 | Турсунова | Лидия   | Сергеевна  | 1980-11-06 12:11:18 | 2 | набережная Крутой реки 149 | +71111111111 | 1234 567891 | 3 |
|  9 | Панков    | Вася    | Дмитриевич | 2006-12-16 12:11:32 | 1 | NULL                       | +79627011087 | 1111 444444 | 2 |
| 10 | Виктор    | Виктор  | Виктор     | 2004-07-02 12:11:41 | 1 | а                          | +79627011087 | 1111 111111 | 2 |

#+begin_export latex
\clearpage
\end{footnotesize}
#+end_export

Полученный экспорт в CSV:

#+INCLUDE: ./employee.csv src text

#+begin_src sql :engine mysql  :dbuser org-mode :dbpassword org-mode :database computerserviceooo :exports results
  SELECT * FROM country;
#+end_src


#+CAPTION: Таблица стран
#+RESULTS:
| id | name      |
|----+-----------|
|  1 | Россия    |
|  2 | США       |
|  3 | Китай     |
|  4 | Франция   |
|  5 | Австралия |


Полученный экспорт в JSON:

#+INCLUDE: ./country.json src json

#+begin_src sql :engine mysql  :dbuser org-mode :dbpassword org-mode :database computerserviceooo :exports results 
  SELECT * FROM position;
#+end_src

#+CAPTION: Таблица должностей
#+ATTR_LATEX: :environment longtable :align |p{1cm}|p{2cm}|p{2cm}|p{3cm}|p{4cm}|
#+RESULTS:
| id | name             | salary | responsibilities               | requirements                                                                              |
|----+------------------+--------+--------------------------------+-------------------------------------------------------------------------------------------|
|  1 | Директор         | 500000 | Руководить                     | NULL                                                                                      |
|  2 | Продавец         |  40000 | Эффективно продавать товары    | 1. Выполнять скрипты\n2. Выполнять нормы продаж\n3. Уведомлять покупателей о новых акциях  |
|  3 | Главный менеджер |  92000 | Следить за работой подчинённых | 1. Оформлять кучу отчётов\n2. Следить за работой подчинённых                              |
|  5 | Стажёр           |  10000 | Учиться работать               | Должен работать под надзором сотрудника-наставника.                                       |
|  6 | Младший менеджер |  30000 | Бумажная работа                | Оформляет товары и занимается большей бумажной работой чем главный менеджер.              |


Полученный экспорт в XML:

#+INCLUDE: ./position.xml src xml


​2. Поработать со всеми строковыми функциями, разобранными на лекции. В качестве параметра в строковых функциях использовать Фамилию, имя, отчество студента. В отчете представить скриншоты с результатом работы функций в MySQL.

Текст запроса:
#+NAME: first
#+begin_src sql :engine mysql  :dbuser org-mode :dbpassword org-mode :database testdb :exports both
	      SELECT CONCAT_WS(' ', 'Меня', 'зовут:', CONCAT(UPPER('п'), LOWER('АНКОВ')), 'Вася,', 'кстати', 'длина', 'моего',
		       'имени:',
		       CONCAT('', LENGTH('Вася'), ','), 'а', 'буква', 'Я', 'находится', 'на', LOCATE('я', 'Вася'), 'позиции.',
		       'Давайте', 'поиграемся', 'с', 'моей', 'фамилией:',
		       LOWER(CONCAT(RIGHT('Панков', 4), SUBSTRING('Панков', 2, 2), SUBSTRING_INDEX('Панков', 'н', 1),
				    LEFT('Панков', 3), '.')), 'Наверное с Кириллом вы незнакомы,',
		       'но его имя отлично преобразуется в', CONCAT(REPLACE('Кирилл', 'рилл', 'лька'), ','),
		       'а ещё классно пишется задом наперёд:', REVERSE('Кирилл')) AS 'RESULT';
#+end_src

Полученный ответ:

#+ATTR_LATEX: :environment longtable :align |p{10cm}|
#+RESULTS: first
| RESULT                                                                                                                                                                                                                                                            |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Меня зовут: Панков Вася, кстати длина моего имени: 8, а буква Я находится на 4 позиции. Давайте поиграемся с моей фамилией: нкованпапан. Наверное с Кириллом вы незнакомы, но его имя отлично преобразуется в Килька, а ещё классно пишется задом наперёд: ллириК |


# Да, я мазахист

​3. Поработать с функциями из Таблицы 1. В качестве параметра выбирается дата рождения студента. В отчете представить скриншоты с результатом работы функций в MySQL.

#+CAPTION: Пример работы некоторых функций
| *Функция*                | *Результат* |
| DAYOFMONTH('2018-05-25') | 25          |
| DAYOFWEEK('2018-05-25')  | 6           |
| DAYOFYEAR('2018-05-25')  | 145         |
| MONTH('2018-05-25')      | 5           |
| YEAR('2018-05-25')       | 2018        |
| QUARTER('2018-05-25')    | 2           |
| WEEK('2018-05-25', 1)    | 21          |
| LAST​_DAY('2018-05-25')   | 2018-05-31  |
| DAYNAME('2018-05-25')    | Friday      |
| MONTHNAME('2018-05-25')  | May         |

Текст запроса:

#+NAME: second
#+begin_src sql :engine mysql  :dbuser org-mode :dbpassword org-mode :database testdb :exports both
	    SELECT CONCAT_WS(' ', 'А вы знали, что я родился', DAYOFMONTH(birthday), MONTHNAME(birthday), YEAR(birthday),
		   'года, в', CONCAT('', DAYNAME(birthday), '.'), 'Это кстати', DAYOFYEAR(birthday), 'день и', WEEK(birthday), 'неделя в году.\n',
		   'А в серьёзной бухгалтерии это', QUARTER(birthday), 'квартал года.', 'Эх, что вам ещё рассказать, что я родился в',
		   MONTH(birthday), 'месяц по счёту или то что последний день этого месяца',
		   CONCAT('', DAYOFMONTH(LAST_DAY(birthday)), '.'),
		   'Видимо придётся заyвершить рассказ.') AS 'RESULT'
		   FROM (SELECT '2003-11-06' AS birthday) AS birthday;
#+end_src

Полученный ответ:

#+ATTR_LATEX: :environment longtable :align |p{10cm}|
#+RESULTS: second
| RESULT                                                                                                   |
|----------------------------------------------------------------------------------------------------------|
| А вы знали, что я родился 6 November 2003 года, в Thursday.  Видимо придётся завершить рассказ.          |
| Это кстати 310 день и 44 неделя в году.                                                                  |
| А в серьёзной бухгалтерии это 4 квартал года.                                                            |
| Эх, что вам ещё рассказать, что я родился в 11 месяц по счёту или то что последний день этого месяца 30. |

​4. Поработать с функциями DATE​_ADD, DATE​_SUB, DATEDIFF. Один из параметров функции - дата рождения студента. В отчете представить скриншоты с результатом работы функций в MySQL.

Текст запросов:

#+NAME: third
#+begin_src sql :engine mysql  :dbuser org-mode :dbpassword org-mode :database testdb :exports both
  SELECT DATE_ADD('2003-11-06', INTERVAL 2 DAY) AS 'День рождения моей прабабушки';
#+end_src


#+NAME: fourth
#+begin_src sql :engine mysql  :dbuser org-mode :dbpassword org-mode :database testdb :exports both
  SELECT YEAR(DATE_SUB('2003-11-06', INTERVAL 24 YEAR)) AS 'Год рождения моих родителей';
#+end_src


#+NAME: fiveth
#+begin_src sql :engine mysql  :dbuser org-mode :dbpassword org-mode :database testdb :exports both
SELECT DATEDIFF('2009-10-20', '2003-11-06') AS 'РАЗНИЦА В ДНЯХ МЕЖДУ РОЖДЕНИМЕМ МНОЙ И МОИМ БРАТОМ';
#+end_src


Полученные ответы:

#+RESULTS: third
| День рождения моей пробабушки |
|-------------------------------|
|                    2003-11-08 |

#+RESULTS: fourth
| Год рождения моих родителей |
|-----------------------------|
|                        1979 |

#+RESULTS: fiveth
| РАЗНИЦА В ДНЯХ МЕЖДУ РОЖДЕНИМЕМ МНОЙ И МОИМ БРАТОМ |
|----------------------------------------------------|
|                                               2175 |

​5. Для одной из таблиц индивидуального задания, где имеется дата рождения(сотрудника, клиента и т.д), выполнить запрос, в котором рядом с датой рождения(тип date) будет столбец с датой рождения с типом timestamp. В отчете представить скриншоты с результатом работы функций в MySQL.

Текст запросов:

#+NAME: sixth
#+begin_src sql :engine mysql  :dbuser org-mode :dbpassword org-mode :database computerserviceooo :exports both
SELECT date_of_birth AS TIMESTAMP, CAST(date_of_birth as DATE) AS DATE FROM employee;
#+end_src

Полученный ответ:

#+RESULTS: sixth
| TIMESTAMP           |       DATE |
|---------------------+------------|
| 2003-12-15 12:10:59 | 2003-12-15 |
| 1999-07-17 12:11:08 | 1999-07-17 |
| 1980-11-06 12:11:18 | 1980-11-06 |
| 2006-12-16 12:11:32 | 2006-12-16 |
| 2004-07-02 12:11:41 | 2004-07-02 |

